name: Playwright CI

on:
  push:
    branches: [master]
  pull_request:
    branches: [master]
  workflow_dispatch:
    inputs:
      BROWSER:
        description: "Browser yang digunakan"
        required: true
        default: "cross"
        type: choice
        options:
          - cross
          - chromium
          - firefox
          - webkit
      WORKERS:
        description: "Jumlah workers parallel"
        required: true
        default: "4"
        type: choice
        options:
          - 1
          - 2
          - 3
          - 4
      GREP:
        description: "Tag atau string untuk --grep filter Playwright"
        required: false
        default: ""
        type: choice
        options:
          - "@"
          - "@login"
          - "@addtocart"
          - "@removecart"
          - "@checkout"
          - "@register"

jobs:
  test:
    runs-on: ubuntu-latest

    container:
      image: mcr.microsoft.com/playwright:v1.49.0-jammy

    env:
      HOME: /root
      HEADLESS: true
      DOCKER_CONFIG: $HOME/.docker

    steps:
      - uses: actions/checkout@v4

      - name: Fix Docker config warning
        run: |
          mkdir -p $HOME/.docker
          echo "{}" > $HOME/.docker/config.json

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 18
          cache: 'npm'

      - name: Install dependencies
        run: npm install

      - name: Write .env file
        run: |
          echo "BASE_URL=${{ vars.BASE_URL }}" >> .env
          echo "TIMEOUT=${{ vars.TIMEOUT }}" >> .env
          echo "RETRIES=${{ vars.RETRIES }}" >> .env
          echo "HEADLESS=${{ env.HEADLESS }}" >> .env
          echo "WORKERS=${{ github.event.inputs.WORKERS || '4' }}" >> .env
          echo "BROWSER=${{ github.event.inputs.BROWSER || 'cross' }}" >> .env

      - name: Run Playwright Tests
        run: |
          if [ -n "${{ github.event.inputs.GREP }}" ]; then
            npm run test -- --grep "${{ github.event.inputs.GREP }}"
          else
            npm run test
          fi

      - name: Upload HTML Report
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: playwright-report
          path: playwright-report/

      - name: Upload Test Results
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: test-results
          path: test-results/
